interface IPermission {
  _id?: string;
  key: string;
  description: string;
}

export enum Permissions {
  VEHICLE_CREATE = "VEHICLE:CREATE",
  VEHICLE_READ = "VEHICLE:READ",
  VEHICLE_UPDATE = "VEHICLE:UPDATE",
  VEHICLE_DELETE = "VEHICLE:DELETE",
  SERVICE_CREATE = "SERVICE:CREATE",
  SERVICE_READ = "SERVICE:READ",
  SERVICE_UPDATE = "SERVICE:UPDATE",
  SERVICE_DELETE = "SERVICE:DELETE",
  SERVICE_REQUEST_CREATE = "SERVICE_REQUEST:CREATE",
  SERVICE_REQUEST_READ = "SERVICE_REQUEST:READ",
  SERVICE_REQUEST_UPDATE = "SERVICE_REQUEST:UPDATE",
  SERVICE_REQUEST_DELETE = "SERVICE_REQUEST:DELETE",
  SERVICE_LOG_CREATE = "SERVICE_LOG:CREATE",
  SERVICE_LOG_READ = "SERVICE_LOG:READ",
  SERVICE_LOG_UPDATE = "SERVICE_LOG:UPDATE",
  SERVICE_LOG_DELETE = "SERVICE_LOG:DELETE",
  CUSTOMER_READ = "CUSTOMER:READ",
  CUSTOMER_UPDATE = "CUSTOMER:UPDATE",
  CUSTOMER_DELETE = "CUSTOMER:DELETE",
}

export default IPermission;
